/**
 * 에러 코드 상수 — API 응답의 error.code에 사용
 */

export const ERR = {
  // Auth
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_PRESET: 'INVALID_PRESET',

  // User / Plan Limits
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  CONCURRENCY_LIMIT: 'CONCURRENCY_LIMIT',
  RULE_SLOT_LIMIT: 'RULE_SLOT_LIMIT',
  ITEM_LIMIT: 'ITEM_LIMIT',

  // Rules
  RULE_NOT_FOUND: 'RULE_NOT_FOUND',
  RULE_FORBIDDEN: 'RULE_FORBIDDEN',

  // Jobs
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_INVALID_TRANSITION: 'JOB_INVALID_TRANSITION',
  JOB_FORBIDDEN: 'JOB_FORBIDDEN',
  CALLBACK_UNAUTHORIZED: 'CALLBACK_UNAUTHORIZED',
  INVALID_ITEM_COUNT: 'INVALID_ITEM_COUNT',

  // General
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
